# Generated by Django 4.2.25 on 2025-10-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='uploaded_audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/audios/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_uid',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
